package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Visual Form JDialog for Editing and Removing/Cancelling Bookings.
 * Designed to match Image 2 layout specifications.
 * Decoupled from logic - exposes components via getters/setters for controllers.
 * 
 * @author dipes
 */
public class BookingEditDialog extends javax.swing.JDialog {

    public BookingEditDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Add manual listener to close when closeLabel is clicked
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispose();
            }
        });
        
        setSize(800, 500);
        setLocationRelativeTo(parent);
        setResizable(false);
    }

    // --- Component Getters ---
    
    public JButton getBtnBookingList() {
        return btnBookingList;
    }

    public JTextField getTxtBookingID() {
        return txtBookingID;
    }

    public JTextField getTxtCarBrand() {
        return txtCarBrand;
    }

    public JLabel getValCarBrandID() {
        return valCarBrandID;
    }

    public JButton getBtnSelectCar() {
        return btnSelectCar;
    }

    public JLabel getValCarID() {
        return valCarID;
    }

    public JLabel getValCarPrice() {
        return valCarPrice;
    }

    public JTextField getTxtCarModel() {
        return txtCarModel;
    }

    public JTextField getTxtCustomerName() {
        return txtCustomerName;
    }

    public JButton getBtnSelectCustomer() {
        return btnSelectCustomer;
    }

    public JLabel getValCustomerID() {
        return valCustomerID;
    }

    public JTextField getTxtPickupCity() {
        return txtPickupCity;
    }

    public JTextField getTxtPickupAddress() {
        return txtPickupAddress;
    }

    public JTextField getTxtPickupDate() {
        return txtPickupDate;
    }

    public JTextField getTxtDropoffCity() {
        return txtDropoffCity;
    }

    public JTextField getTxtDropoffAddress() {
        return txtDropoffAddress;
    }

    public JTextField getTxtDropoffDate() {
        return txtDropoffDate;
    }

    public JButton getBtnRemove() {
        return btnRemove;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public JTextField getTxtTotalPrice() {
        return txtTotalPrice;
    }

    public JButton getBtnCalculate() {
        return btnCalculate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        selectBookingPanel = new javax.swing.JPanel();
        btnBookingList = new javax.swing.JButton();
        lblBookingID = new javax.swing.JLabel();
        txtBookingID = new javax.swing.JTextField();
        selectCarPanel = new javax.swing.JPanel();
        lblSelectCarTitle = new javax.swing.JLabel();
        lblCarBrand = new javax.swing.JLabel();
        txtCarBrand = new javax.swing.JTextField();
        lblCarBrandID = new javax.swing.JLabel();
        valCarBrandID = new javax.swing.JLabel();
        lblCarField = new javax.swing.JLabel();
        btnSelectCar = new javax.swing.JButton();
        lblCarSelectID = new javax.swing.JLabel();
        valCarID = new javax.swing.JLabel();
        lblCarPrice = new javax.swing.JLabel();
        valCarPrice = new javax.swing.JLabel();
        lblCarModel = new javax.swing.JLabel();
        txtCarModel = new javax.swing.JTextField();
        selectCustomerPanel = new javax.swing.JPanel();
        lblSelectCustomerTitle = new javax.swing.JLabel();
        lblCustomerField = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        btnSelectCustomer = new javax.swing.JButton();
        lblCustomerIDField = new javax.swing.JLabel();
        valCustomerID = new javax.swing.JLabel();
        pickupLocationPanel = new javax.swing.JPanel();
        lblPickupHeader = new javax.swing.JLabel();
        lblPickupCity = new javax.swing.JLabel();
        txtPickupCity = new javax.swing.JTextField();
        lblPickupAddress = new javax.swing.JLabel();
        txtPickupAddress = new javax.swing.JTextField();
        lblPickupDate = new javax.swing.JLabel();
        txtPickupDate = new javax.swing.JTextField();
        dropoffLocationPanel = new javax.swing.JPanel();
        lblDropoffHeader = new javax.swing.JLabel();
        lblDropoffCity = new javax.swing.JLabel();
        txtDropoffCity = new javax.swing.JTextField();
        lblDropoffAddress = new javax.swing.JLabel();
        txtDropoffAddress = new javax.swing.JTextField();
        lblDropoffDate = new javax.swing.JLabel();
        txtDropoffDate = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblTotalPrice = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(245, 245, 245));
        mainPanel.setLayout(null);

        headerPanel.setBackground(new java.awt.Color(30, 39, 49));
        headerPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Booking Edit / Remove");
        headerPanel.add(titleLabel);
        titleLabel.setBounds(20, 10, 400, 30);

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("X");
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        headerPanel.add(closeLabel);
        closeLabel.setBounds(760, 10, 30, 30);

        mainPanel.add(headerPanel);
        headerPanel.setBounds(0, 0, 800, 50);

        selectBookingPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectBookingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        selectBookingPanel.setLayout(null);

        btnBookingList.setBackground(new java.awt.Color(43, 124, 245));
        btnBookingList.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBookingList.setForeground(new java.awt.Color(255, 255, 255));
        btnBookingList.setText("Booking List");
        btnBookingList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectBookingPanel.add(btnBookingList);
        btnBookingList.setBounds(10, 25, 120, 30);

        lblBookingID.setText("ID:");
        selectBookingPanel.add(lblBookingID);
        lblBookingID.setBounds(150, 30, 30, 20);

        txtBookingID.setEditable(false);
        txtBookingID.setText("00");
        selectBookingPanel.add(txtBookingID);
        txtBookingID.setBounds(180, 25, 80, 30);

        mainPanel.add(selectBookingPanel);
        selectBookingPanel.setBounds(20, 70, 460, 80);

        selectCarPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectCarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        selectCarPanel.setLayout(null);

        lblSelectCarTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSelectCarTitle.setForeground(new java.awt.Color(43, 124, 245));
        lblSelectCarTitle.setText("Select a Car");
        selectCarPanel.add(lblSelectCarTitle);
        lblSelectCarTitle.setBounds(10, 10, 200, 20);

        lblCarBrand.setText("Brand:");
        selectCarPanel.add(lblCarBrand);
        lblCarBrand.setBounds(10, 40, 60, 20);
        selectCarPanel.add(txtCarBrand);
        txtCarBrand.setBounds(70, 38, 320, 25);

        lblCarBrandID.setText("ID:");
        selectCarPanel.add(lblCarBrandID);
        lblCarBrandID.setBounds(400, 40, 20, 20);

        valCarBrandID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valCarBrandID.setText("1");
        selectCarPanel.add(valCarBrandID);
        valCarBrandID.setBounds(425, 40, 30, 20);

        lblCarField.setText("Car:");
        selectCarPanel.add(lblCarField);
        lblCarField.setBounds(10, 80, 60, 20);

        btnSelectCar.setBackground(new java.awt.Color(43, 124, 245));
        btnSelectCar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnSelectCar.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectCar.setText("Select Car");
        btnSelectCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectCarPanel.add(btnSelectCar);
        btnSelectCar.setBounds(70, 78, 100, 25);

        lblCarSelectID.setText("ID:");
        selectCarPanel.add(lblCarSelectID);
        lblCarSelectID.setBounds(180, 80, 20, 20);

        valCarID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valCarID.setText("000");
        selectCarPanel.add(valCarID);
        valCarID.setBounds(200, 80, 40, 20);

        lblCarPrice.setText("Price:");
        selectCarPanel.add(lblCarPrice);
        lblCarPrice.setBounds(250, 80, 40, 20);

        valCarPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valCarPrice.setText("000");
        selectCarPanel.add(valCarPrice);
        valCarPrice.setBounds(295, 80, 60, 20);

        lblCarModel.setText("Model:");
        selectCarPanel.add(lblCarModel);
        lblCarModel.setBounds(10, 115, 60, 20);
        selectCarPanel.add(txtCarModel);
        txtCarModel.setBounds(70, 113, 320, 25);

        mainPanel.add(selectCarPanel);
        selectCarPanel.setBounds(20, 160, 460, 150);

        selectCustomerPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectCustomerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        selectCustomerPanel.setLayout(null);

        lblSelectCustomerTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSelectCustomerTitle.setForeground(new java.awt.Color(43, 124, 245));
        lblSelectCustomerTitle.setText("Select Customer");
        selectCustomerPanel.add(lblSelectCustomerTitle);
        lblSelectCustomerTitle.setBounds(10, 10, 200, 20);

        lblCustomerField.setText("Customer:");
        selectCustomerPanel.add(lblCustomerField);
        lblCustomerField.setBounds(10, 40, 70, 20);
        selectCustomerPanel.add(txtCustomerName);
        txtCustomerName.setBounds(80, 38, 260, 25);

        btnSelectCustomer.setBackground(new java.awt.Color(43, 124, 245));
        btnSelectCustomer.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnSelectCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectCustomer.setText("Select Customer");
        btnSelectCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectCustomerPanel.add(btnSelectCustomer);
        btnSelectCustomer.setBounds(350, 38, 100, 25);

        lblCustomerIDField.setText("ID:");
        selectCustomerPanel.add(lblCustomerIDField);
        lblCustomerIDField.setBounds(350, 10, 20, 20);

        valCustomerID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valCustomerID.setText("000");
        selectCustomerPanel.add(valCustomerID);
        valCustomerID.setBounds(380, 10, 40, 20);

        mainPanel.add(selectCustomerPanel);
        selectCustomerPanel.setBounds(20, 320, 460, 80);

        pickupLocationPanel.setBackground(new java.awt.Color(255, 255, 255));
        pickupLocationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        pickupLocationPanel.setLayout(null);

        lblPickupHeader.setBackground(new java.awt.Color(43, 124, 245));
        lblPickupHeader.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPickupHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblPickupHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPickupHeader.setText("Pick Up Location & Date");
        lblPickupHeader.setOpaque(true);
        pickupLocationPanel.add(lblPickupHeader);
        lblPickupHeader.setBounds(0, 0, 280, 30);

        lblPickupCity.setText("City:");
        pickupLocationPanel.add(lblPickupCity);
        lblPickupCity.setBounds(10, 40, 60, 20);
        pickupLocationPanel.add(txtPickupCity);
        txtPickupCity.setBounds(10, 60, 260, 25);

        lblPickupAddress.setText("Address:");
        pickupLocationPanel.add(lblPickupAddress);
        lblPickupAddress.setBounds(10, 90, 80, 20);
        pickupLocationPanel.add(txtPickupAddress);
        txtPickupAddress.setBounds(10, 110, 260, 25);

        lblPickupDate.setText("Date:");
        pickupLocationPanel.add(lblPickupDate);
        lblPickupDate.setBounds(10, 140, 60, 20);
        pickupLocationPanel.add(txtPickupDate);
        txtPickupDate.setBounds(70, 140, 200, 25);

        mainPanel.add(pickupLocationPanel);
        pickupLocationPanel.setBounds(500, 70, 280, 175);

        dropoffLocationPanel.setBackground(new java.awt.Color(255, 255, 255));
        dropoffLocationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        dropoffLocationPanel.setLayout(null);

        lblDropoffHeader.setBackground(new java.awt.Color(43, 124, 245));
        lblDropoffHeader.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDropoffHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblDropoffHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDropoffHeader.setText("Drop Off Location & Date");
        lblDropoffHeader.setOpaque(true);
        dropoffLocationPanel.add(lblDropoffHeader);
        lblDropoffHeader.setBounds(0, 0, 280, 30);

        lblDropoffCity.setText("City:");
        dropoffLocationPanel.add(lblDropoffCity);
        lblDropoffCity.setBounds(10, 40, 60, 20);
        dropoffLocationPanel.add(txtDropoffCity);
        txtDropoffCity.setBounds(10, 60, 260, 25);

        lblDropoffAddress.setText("Address:");
        dropoffLocationPanel.add(lblDropoffAddress);
        lblDropoffAddress.setBounds(10, 90, 80, 20);
        dropoffLocationPanel.add(txtDropoffAddress);
        txtDropoffAddress.setBounds(10, 110, 260, 25);

        lblDropoffDate.setText("Date:");
        dropoffLocationPanel.add(lblDropoffDate);
        lblDropoffDate.setBounds(10, 140, 60, 20);
        dropoffLocationPanel.add(txtDropoffDate);
        txtDropoffDate.setBounds(70, 140, 200, 25);

        mainPanel.add(dropoffLocationPanel);
        dropoffLocationPanel.setBounds(500, 255, 280, 175);

        btnRemove.setBackground(new java.awt.Color(237, 40, 54));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove / Cancel Booking");
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.add(btnRemove);
        btnRemove.setBounds(20, 450, 180, 35);

        btnEdit.setBackground(new java.awt.Color(43, 124, 245));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Booking");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.add(btnEdit);
        btnEdit.setBounds(210, 450, 120, 35);

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTotalPrice.setText("Total Price:");
        mainPanel.add(lblTotalPrice);
        lblTotalPrice.setBounds(480, 455, 80, 25);

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtTotalPrice.setText("0000");
        mainPanel.add(txtTotalPrice);
        txtTotalPrice.setBounds(565, 452, 90, 30);

        btnCalculate.setBackground(new java.awt.Color(43, 124, 245));
        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("calculate");
        btnCalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.add(btnCalculate);
        btnCalculate.setBounds(665, 452, 115, 30);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 800, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSelectCar;
    private javax.swing.JButton btnSelectCustomer;
    private javax.swing.JButton btnBookingList;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel dropoffLocationPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblBookingID;
    private javax.swing.JLabel lblCarBrand;
    private javax.swing.JLabel lblCarBrandID;
    private javax.swing.JLabel lblCarField;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCarPrice;
    private javax.swing.JLabel lblCarSelectID;
    private javax.swing.JLabel lblCustomerIDField;
    private javax.swing.JLabel lblCustomerField;
    private javax.swing.JLabel lblDropoffAddress;
    private javax.swing.JLabel lblDropoffCity;
    private javax.swing.JLabel lblDropoffDate;
    private javax.swing.JLabel lblDropoffHeader;
    private javax.swing.JLabel lblPickupAddress;
    private javax.swing.JLabel lblPickupCity;
    private javax.swing.JLabel lblPickupDate;
    private javax.swing.JLabel lblPickupHeader;
    private javax.swing.JLabel lblSelectCarTitle;
    private javax.swing.JLabel lblSelectCustomerTitle;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pickupLocationPanel;
    private javax.swing.JPanel selectBookingPanel;
    private javax.swing.JPanel selectCarPanel;
    private javax.swing.JPanel selectCustomerPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField txtBookingID;
    private javax.swing.JTextField txtCarBrand;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDropoffAddress;
    private javax.swing.JTextField txtDropoffCity;
    private javax.swing.JTextField txtDropoffDate;
    private javax.swing.JTextField txtPickupAddress;
    private javax.swing.JTextField txtPickupCity;
    private javax.swing.JTextField txtPickupDate;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JLabel valCarBrandID;
    private javax.swing.JLabel valCarID;
    private javax.swing.JLabel valCarPrice;
    private javax.swing.JLabel valCustomerID;
    // End of variables declaration//GEN-END:variables
}
